<?php

return [
    'products' => [
            'Obst' => [
                'apfel' => 'Apfel',
                'banane' => 'Bananen',
                'clementine' => 'Clementine',
                'erdbeere' => 'Erdbeeren',
                'heidelbeere' => 'Heidelbeeren',
                'orange' => 'Orange',
            ],
            'Gemüse' => [
                'kartoffeln' => 'Kartoffeln',
                'möhren' => 'Möhren',
                'paprika' => 'Paprika',
                'tomaten' => 'Tomaten',
            ],
            'Sonstiges' => [
                'thunfisch' => 'Thunfisch',
                'eier' => 'Eier',
            ]
        ],

        'months' => [
            'Jan' => 1,
            'Feb' => 2,
            'Mär' => 3,
            'Apr' => 4,
            'Mai' => 5,
            'Jun' => 6,
            'Jul' => 7,
            'Aug' => 8,
            'Sep' => 9,
            'Okt' => 10,
            'Nov' => 11,
            'Dez' => 12,
        ],
        'articles' => [
            // Obst
            'Heidelbeere' => 'Heidelbeeren',
            'Pflaumen dunkel' => 'Pflaumen',
            'Apfel rot' => 'Apfel',
            'Apfel pink kg' => 'Apfel',
            'Wetterapfel' => 'Apfel',
            'Apfelmus gezuckert' => 'Apfelmus',
            'Saftorangen' => 'Orangen',
            'Orangen 1,5kg' => 'Orangen',
            'Beerenteller' => 'TK Beerenteller',
            'Satsum' => 'Clementinen',
            'Clementine' => 'Clementinen',
            'FairtradeBanane' => 'Bananen',
            'Feige' => 'Feigen',
            'TraubHell' => 'Trauben',
            'Trauben' => 'Trauben',
            'Pflaume dunk kg' => 'Pflaumen kg',
            'Pflaume blau kg' => 'Pflaumen kg',
            'Pflaume gelb kg' => 'Pflaumen kg',
            'Honigpomelo' => 'Honigpomelo',
            'Birnen, Rocha' => 'Birnen',
            // Fleisch
            'Hähn.-Platte Diavolo' => 'Hähnchen-Platte',
            'Hähnchenbr .Filet608g' => 'Hähnchenbrustfilet',
            'Hähnchenbrust ungega' => 'Hähnchenbrust',
            'Hähn.-Geschnetzeltes' => 'Hähnchen-Geschnetzeltes',
            'Cevapcici' => 'Cevapcici',
            'Kochschinken' => 'Kochschinken',
            'Chorizo' => 'Chorizo',
            'Wiener' => 'Wiener Würstchen',
            'Prosciutto' => 'Prosciutto',
            'Leberw' => 'Leberwurst',
            'Hackfleisch' => 'Hackfleisch',
            'Edelsalami' => 'Edelsalami',
            'Käse-Paprika Würst' => 'Käse-Paprika Würstchen',
            // Gemüse
            'Kaisergem. Mix 1888g' => 'Kaisergemüse',
            'Blattsalat-Rohk.-Mix' => 'Blattsalat',
            'Champign' => 'Champignon',
            'Möhren Ikg' => 'Möhren 1 kg',
            'süßkartoffeln' => 'Süßkartoffeln',
            'Bio Feldsalat' => 'Feldsalat',
            'Bio Geh.Tomaten Ore.' => 'Gehackte Tomaten',
            'Gewürzgurken Auslese' => 'Gewürzgurken',
            'Grüne Oliven entst.' => 'Grüne Oliven',
            'Zwiebeln gelb' => 'Zwiebeln',
            'Speisefrühkartoffeln' => 'Kartoffeln',
            'Speisekartoffeln' => 'Kartoffeln',
            'Gurke Stk' => 'Gurken',
            'Rucola 125g' => 'Rucola',
            'TomateStrau. kg' => 'Tomaten kg',
            'Rosenkohl' => 'Rosenkohl',
            'Kürbis' => 'Kürbis',
            'Kopfsalat' => 'Kopfsalat',
            'Multicol. Salat' => 'Multicolor Salat',
            // Fisch
            'Thunfisch' => 'Thunfisch',
            'Räucherlachs' => 'Räucherlachs',
            'Heringsfilets Tomate' => 'Heringsfilet',
            'Lachsfiletportionen' => 'Lachsfilet',
            'MSC Filet Ext. Kross' => 'MSC Filet Kross',
            'MSCSchlemm. Bordelai' => 'MSC Schlemmerfilet',
            'Appel Her. Paprika' => 'Heringsfilet',
            'Matjesfil' => 'Matjesfilet',
            // Milchprodukte
            'Biol.Natur.3, 8%' => 'Bio Joghurt Natur',
            'Creme Fraiche' => 'Creme Fraiche',
            'Griech. Joghurt 10%' => 'Griechischer Joghurt',
            'Jogh. Mild' => 'Joghurt 500g',
            'Joghurt Mild' => 'Joghurt 500g',
            'Kerrygold Butter' => 'Butter',
            'Kerrygold gesalzen' => 'Butter',
            'Schlagsahne' => 'Schlagsahne',
            'Speisequark' => 'Speisequark',
            'Vollmilch' => 'Milch',
            'Frischmilch' => 'Milch',
            'Bärenm.' => 'Bärenmilch',
            'H-Sahne' => 'Schlagsahne hocherh.',
            'Kefir 1,5%' => 'Kefir',
            // Käse
            'Feta 288g' => 'Feta 200g',
            'Hirtenkäse' => 'Hirtenkäse',
            'Kör.Frischk.' => 'Körniger Frischkäse',
            'Kräuterquark' => 'Kräuterquark',
            'Mozzarella' => 'Mozzarella',
            'Bergader Mild Nussig' => 'Bergader Käse Nussig',
            'Bergader Würzig' => 'Bergader Käse Würzig',
            // Snacks
            'Arriba Edelcacao 85%' => 'Arriba Edelvacao',
            'Cashewkerne 288g' => 'Cashewkerne',
            'Cremissimo Straccia' => 'Cremissimo Stracciatella',
            'Cremissi.Kirsch' => 'Cremissimo Kirsch',
            'Cremissimo Heidelbee' => 'Cremissimo Heidelbeere',
            'Jogh. & Waffelwürfel' => 'Joghurt & Waffelwürfel',
            'Müller Milchr' => 'Müller Milchreis',
            'Müller H.Protein' => 'Müller Milchreis',
            'Pudding Vanille' => 'Puddingpulver Vanille',
            'Salzbrezeln' => 'Salzbrezeln',
            'Stapelchips Sour Cr.' => 'Stapelchips',
            'Stud.-Futter Classic' => 'Studentenfutter',
            'Sultaninen Südafrika' => 'Sultaninen',
            'Walnusskerne' => 'Walnusskerne',
            'Pring' => 'Pringles',
            'Katjes' => 'Katjes',
            'Traube-Nuß Sch' => 'Schokolade Traube-Nuß',
            // Getreideprodukte
            'Bandnudeln 2 Ei' => 'Bandnudeln',
            'Bio Spaghetti HNG' => 'Bio Spaghetti',
            'Bulgur lose' => 'Bulgur',
            'Haferf. Kern' => 'Haferflocken',
            'Haferflocken zart' => 'Haferflocken',
            'Mega Burger' => 'Burgerbrötchen',
            'Rindfl. Maultaschen' => 'Maultaschen',
            'Roggenkruste' => 'Roggenkruste',
            'Roggenvollkornbrot' => 'Roggenvollkornbrot',
            'Spaghetti 508g' => 'Spaghetti',
            'Vollkorn Sonnen .Brot' => 'Sonnenblumenbrot',
            'Weizenmehl 1ikg' => 'Weizenmehl',
            'Parboiled Reis' => 'Reis',
            'Milchreis 588g' => 'Milchreis 500g',
            'BioDinkel-Krust' => 'Krustenbrot',
            'Weltmeisterbr.' => 'Weltmeisterbrötchen',
            'Rosenbröt.dunke' => 'Rosenbrötchen',
            'Crustini 908g' => 'Crustini',
            'Haferfl. Zart' => 'Haferflocken',
            // Fertigprodukte
            'Frühlingsroll. Hähn.' => 'Frühlingsrolle',
            'Knusperfr. Peper.' => 'Pepperoni Pizza',
            'Dr. Oetk Rist. Diav' => 'Diavolo Pizza',
            'Pizzateig & Sauce' => 'Pizzateig',
            'UncleB Kantonesisch' => 'UncleBen\'s Kantonesisch',
            'UncleBen\'s Süß Sauer' => 'UncleBen\'s Süß-Sauer',
            'BensOr.Süß-Sau. o.Zu' => 'UncleBen\'s Süß-Sauer',
            'Dr.Oetker Pizza' => 'Dr. Oetker Pizza',
            'Dr.Oetker Tradiziona' => 'Dr. Oetker Pizza',
            'Dr.Oetker Ris.Hawaii' => 'Dr. Oetker Pizza',
            'Dr.Oetker Spinaci' => 'Dr. Oetker Pizza',
            'Wagner Backf.Hähnche' => 'Wagner Pizza',
            'Erasco Lins. Eintopf' => 'Linseneintopf',
            'Sushi' => 'Sushi',
            // Getränke
            'Naturtrübes Radler' => 'Radler 0,5l',
            'Naturradler Apfel' => 'Radler 0,5l',
            'Radler Naturtrüb' => 'Radler 0,33l',
            'Radler 6x8,51' => 'Radler 6 x 0,5l',
            'Kaffee Auslese klas.' => 'Kaffee',
            'Jacobs Krön.' => 'Kaffee',
            'Kamillentee in Tüte' => 'Kamillentee',
            // Sonstiges
            'Eier' => 'Eier',
            'Spannbettlak' => 'Spannbettlaken',
            'WC-Bürstenga' => 'WC Bürste',
            'Backpapier' => 'Backpapier',
            'Colorwaschmittel1,11' => 'Colorwaschmittel',
            'Geschirr Tabs' => 'Spülmaschinentabs',
            'Küchentücher 31g.' => 'Küchentücher',
            'Müllbeutel 251' => 'Müllbeutel 25l',
            'Purio Müllb. 28er' => 'Müllbeutel 50l',
            'Schwammtuch 5er' => 'Schwammtuch 5er',
            'Tiefkühltasche' => 'Tiefkühltasche',
            'Toilettenpapier Alg' => 'Toilettenpapier',
            'Rapsöl' => 'Rapsöl',
            'Sonnenblumenöl' => 'Sonnenblumenöl',
            'HonigFeincremig' => 'Honig',
            'Koriander gemahlen' => 'Koriander',
            'Topfkr.Basil.' => 'Basilikum',
            'Pfeffer bunt' => 'Pfeffer',
            'Pfeffer geschrotet' => 'Pfeffer',
            'Thymian gerebelt' => 'Thymian',
            'Anti Schup.Sh.' => 'Antischuppen Shampoo',
            'Zahncreme Seidenweiß' => 'Zahncreme',
            'Cremeseife Honig' => 'Seife Honig',
            'Zucker 1ikg' => 'Zucker',
            'Vanillinzucker 128g' => 'Vanillinzucker',
        ]
    ];
